[FEAT] 밥먹언 앱 내 사용되는 색상을 UIColorExtension으로 추가
DeveloperAcademy-POSTECH/MC3-Team3-Puhaha pull request #20
Opened 2022-07-21 10:32 UTC by teethemoji

- bobRed, bobPurple, bobBlue, bobYellow, bobBlack 추가
- 이후에 색상 변경이 필요하다면 return 값만 수정하면 ok

 ## ✅ 구현/변경 사항 및 이유

기존에는 toolColors 배열에 저장되어 있는 값을 불러오느라 인덱스 값을 매번 알아야 했는데 그럴 필요 없이 바로 사용하기 좋게 고유 이름들을 붙여주었습니다.

이후에 배정된 색상값이 변경되더라도 UIColor+Extension.swift 파일 내 코드만 수정하면 됩니다.

2022-07-21 10:46 UTC, lenamin requested changes
감사합니다 티모👍

2022-07-21 10:46 UTC, lenamin commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +    }
밥레드 대신에 tag의 색상임을 알 수 있는 변수명은 어떨까요? tagColorRed라고 지으면 태그의 색상임을 더 직관적으로 알 수 있을 것 같습니다!

2022-07-21 11:24 UTC, teethemoji commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +    }
태그 이외에도 포크 제작 뷰나 하단 탭바 같이 다른 뷰에서도 사용되는지라 tag를 붙이는 변수명은 다소 맞지 않을 것 같습니다..!

2022-07-21 12:16 UTC, lenamin commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +    }
그럼 밥 대신 appRed는 어떤가요? 
밥은 다른 사람이 봤을 때 바로 알아보기 어려울 수 있을 것 같습니다 😀

2022-07-22 09:30 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +    }
로그인 뷰 background 노란색 색상을 uicolor 인덱스 접근해서 썼었는데, 올라가고 나서 제가 다시 수정해야겠네요! 🥹 + 색상 커스텀 멋져요 😘

2022-07-22 09:31 UTC, SohyeonKim-dev approved these changes

2022-07-22 10:05 UTC, teethemoji commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +    }
파일 하단에 toolColors 배열을 유지시켜두었기때문에 바로 교체하지 않으셔도 됩니다ㅎ

2022-07-22 13:19 UTC, JIW00NG approved these changes

2022-07-22 13:19 UTC, JIW00NG commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +    }
저렇게 하는거 좋은거 같아요!
근데 asset에 등록하는거랑 저렇게 하는거랑 뭐가 더 좋은건가요?

2022-07-22 13:19 UTC, JIW00NG commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +#if DEBUG
구웃👍

2022-07-22 13:20 UTC, JIW00NG reviewed
approve받고 머지하기 전에 메인꺼를 본인 브랜치로 머지 하고 다시 푸쉬해주세요

2022-07-22 13:22 UTC, JIW00NG requested changes
해당 pr부분이 머지될 때 메인이 변경되는 경우 컴플릭트가 생길 수 있기 때문에 머지하기 전에 메인꺼를 본인 브랜치로 머지 하고 다시 푸쉬해주세요.

2022-07-23 08:39 UTC, teethemoji commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +    }
후자 방법은 제가 몰랐는데 방금 찾아봤더니
전자의 경우는 지금처럼 바로 코드로 작성 후 `UIColor.bobRed ` 이런 식으로 사용이 가능한데
후자의 경우는 Asset에서 ColorSet을 새로 만들어내고 인스펙터 창에서 따로 더 만져주는 과정이 더해지고 사용할 때에는 `UIColor(named: "bobRed")` 이런 식으로 사용하네요
제가 보기엔 지금처럼 코드로 바로 작성해서 사용하는것이 더 간편하고 이후 수정할 때에도 용이할 것 같습니다.

2022-07-23 08:57 UTC, teethemoji commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +    }
색상명 앞에 `custom`을 붙이는 것으로 결정되어 수정 완료했습니다👍

2022-07-25 07:52 UTC, JIW00NG commented
현재 충돌이 나고 있어서 충돌 해결해주세요!!!

2022-07-26 00:40 UTC, lenamin approved these changes
수고하셨습니다~!

2022-07-26 00:40 UTC, JIW00NG approved these changes

2022-07-26 00:40 UTC, JIW00NG commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +extension UIColor {
이런 식으로 컬러 지정한거 좋아요~

2022-07-26 00:51 UTC, merged