#3 main view pull request
DeveloperAcademy-POSTECH/MC3-Team3-Puhaha pull request #21
Opened 2022-07-22 13:13 UTC by JIW00NG

## ✅ 관련 이슈

 
#3 MainView  구현 with dummy data

 ## ✅ 구현/변경 사항 및 이유

 
* horizontal CollectionView를 이용한 filter
![Simulator Screen Shot - iPhone 13 mini - 2022-07-22 at 20 41 05](https://user-images.githubusercontent.com/56468120/180432348-f4c76cf2-d240-4b25-b34e-36fdec02f8f0.png)

* horizontal CollectionView를 이용한 음식 사진 뷰(Tag, 음식 사진, 사진 올린 사람 이름 표시)
-> TableView는 Horizontal scroll이 불가능하여 CollectionView 사용
![Simulator Screen Shot - iPhone 13 mini - 2022-07-22 at 20 41 05 copy 2](https://user-images.githubusercontent.com/56468120/180432444-b69d15ca-8cbb-4c1a-b212-d370630dbf17.png)

* 상단 현재 날짜 표시

* Tab Bar 추가 
![Simulator Screen Shot - iPhone 13 mini - 2022-07-22 at 20 41 05 copy 4](https://user-images.githubusercontent.com/56468120/180432591-04855ab3-0823-4d1f-a8ee-36f313e632f1.png)

 ## ✅ PR Point

 
* mainView는 CollectionView가 가장 메인입니다. MainViewController에 있는 collectionView와 collectionViewCell 클래스를 이용하여 구현 했으며 CollectionView에 대해 궁금하다면 참고하시기 바랍니다.   
* 메인 화면의 경우 MainTabBarViewController가 될 것으로 보이며 통계 화면이 추가된다면 TabBarViewController에서 추가하시면 되겠습니다.   
* constraints 설정을 조금 다르게 했습니다. 다른 분들이 이렇게 하는게 좋다고 하셔서 한번 해봤어요.

```swift
// todayDateLabel.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor).isActive = true
// todayDateLabel.leadingAnchor.constraint(equalTo: super.view.leadingAnchor, constant: 22).isActive = true

NSLayoutConstraint.activate([
            todayDateLabel.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
            todayDateLabel.leadingAnchor.constraint(equalTo: super.view.leadingAnchor, constant: 22)
])
```

 ## ✅ 참고 사항

 
![Simulator Screen Shot - iPhone 13 mini - 2022-07-22 at 20 41 05](https://user-images.githubusercontent.com/56468120/180432093-92fb8a09-659b-4431-8b31-ea2215cd9d7a.png)

2022-07-22 16:45 UTC, lenamin requested changes
고생많으셨습니다~!!

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainTabViewController.swift
> +
불필요한 개행은 지워주신다면 가독성이 더 좋아질 것 같습니다!

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainTabViewController.swift
> + 출처: https://velog.io/@leejh3224/iOS-TabBar-shadow-커스터마이징-trjugzee87
출처 남겨주신 것 좋아요

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainTabViewController.swift
> +    // Sketch 스타일의 그림자를 생성하는 유틸리티 함수
코드를 보고 내용 파악이 가능하다면 주석은 없어도 되지 않을까요? 
꼭 필요하다면 `///` 을 써서 호출하는 곳에서도 알 수 있게 하면 좋을 것 같습니다 :)

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainViewController.swift
> +
개행을 하신 이유가 있을까요? 👀

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainViewController.swift
> +    private var mealCollectionView: UICollectionView = {
카드임을 알 수 있는 변수명이 들어간다면 코드를 읽을 때 이해가 더 쉬울 것 같습니다!

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainViewController.swift
> +        collectionView.register(FamilyFilterCollectionViewCell.self, forCellWithReuseIdentifier: "FamilyFilterCollectionViewCell")
reuse identifier는 미리 선언해두고 불러오면 어떨까요?

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainViewController.swift
> +
이곳의 개행 또한 의도된 것일까요?

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Controllers/StatisticViewController.swift
> +        // Do any additional setup after loading the view.
불필요한 주석이라면 없는 것이 가독성이 더 좋을 것 같아요!

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Models/Family.swift
> +#endif
더미 데이터 처리를 이렇게 할 수 있군요. 너무 좋습니다!!

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Models/Meal.swift
> +import UIKit
UIKit 만 있어도 되지 않을까요?

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Views/FamilyFilterCollectionViewCell.swift
> +    }
무엇을 configure 하는지 변수명에 나타나있으면 코드 읽을 때 더 좋을 것 같습니다!

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Views/MealCollectionViewCell.swift
> +        imageView.translatesAutoresizingMaskIntoConstraints = false
false 해주는 부분이 어떤 곳에서는 constraint 설정 항목에 따로 들어가있고, 여기서는 각 변수에 들어가있는데 통일해주면 나중에 빠진 부분을 체크하기 더 좋지 않을까요? 😃

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Views/MealCollectionViewCell.swift
> +    var thirdTagLabel = TagLabel()
first, second, third는 각각 어떤 태그를 의미하나요?

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Views/MealCollectionViewCell.swift
> +            mealImageView.topAnchor.constraint(equalTo: topAnchor),
이런식으로 한번에 activate 해주는 것도 좋네요!!

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainTabViewController.swift
> +        blur: CGFloat = 4
파라미터가 많은 경우에 이렇게 개행하니 가독성이 정말 좋네요!!

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Controllers/StatisticViewController.swift
> +
이 부분도,, 필요하지 않다면 지워주신다면 좋을 것 같습니다 ,,

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
> +//  Date+Today.swift
파일명에 +는 어떤 의미일까요?

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Global/UIViews/TagLabel.swift
> +        tagBackground.frame = CGRect(x: 0, y: 0, width: tagLabel.intrinsicContentSize.width / 2 + tagLabel.intrinsicContentSize.width, height: tagLabel.intrinsicContentSize.height + tagLabel.intrinsi
👍👍

2022-07-22 16:45 UTC, lenamin commented on Puhaha/Puhaha/Views/FamilyFilterCollectionViewCell.swift
> +    private var userIcon: UIImageView = {
Image 라는 것을 알 수 있는 변수명은 어떨까요?

2022-07-23 02:40 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/MainTabViewController.swift
> +    // Sketch 스타일의 그림자를 생성하는 유틸리티 함수
지우고 다시 올릴게요!

2022-07-23 02:40 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/MainTabViewController.swift
> +
알겠습니다!

2022-07-23 05:15 UTC, lenamin approved these changes
빠른 반영 감사합니다 고생많으셨습니다!

2022-07-23 05:15 UTC, lenamin commented on Puhaha/Puhaha/Views/MealCardCollectionViewCell.swift
> +        }
오호 이제 무슨 의민지 이해가 갔습니다!

2022-07-23 06:20 UTC, SohyeonKim-dev approved these changes
메인 CCCCCCCTO의 작업량,,, 레전드입니다.. 수고하셨어요! 👏

2022-07-23 06:20 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/MainTabViewController.swift
> + 출처: https://velog.io/@leejh3224/iOS-TabBar-shadow-커스터마이징-trjugzee87
동의합니다! ✌️ 저도 앞으로 코드 가져올 때 출처를 같이 적어둬야겠어요! :)

2022-07-23 06:20 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/MainViewController.swift
> +        }
else로 넘어가는 collectionView는 familyFilterCollectionView 인거죠?!

2022-07-23 06:20 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/StatisticViewController.swift
> +    }()
저희 첫번째 출시 버전으로는, 설정 뷰 내용들을 이곳에 넣는 건 어떨까요? 
메인 우측 탭바 전체를 준비중으로 두는게, 완성도가 떨어지는 것 같아 걱정됩니다. 🥲
(+생각해보니 이건 user flow에 영향을 줄 수도 있을 것 같아서, 팀원들이랑 더 논의가 필요할 것 같네요,, 자그마한 의견.. 이었습니다.)

2022-07-23 06:20 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Models/Family.swift
> +#endif
이것이 CCCCCCTO의 바이브 . 👏

2022-07-23 06:20 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Models/Meal.swift
> +}
욱이는 . . 한참 전부터,, 데이터 구조를 짜고 계셨군요.... .. . wow
메인 PR이 지금 올라온 것에는 다-아 이유가 있었다. 👏👏
이제 이런 부분들이 어제 정의한 데이터 모델 구조로 수정되는건가요?

2022-07-23 09:32 UTC, teethemoji commented on Puhaha/Puhaha/Models/Family.swift
> +    static var sampleFamilyMemebers = [
`sampleFamilyMemebers` -> `sampleFamilyMembers` 수정 부탁드립니다!

2022-07-25 00:49 UTC, teethemoji approved these changes
수고하셨습니다 머지해주세요👍

2022-07-25 02:19 UTC, merged