[FEAT] 콕 찌르기 도구 제작 뷰 구현
DeveloperAcademy-POSTECH/MC3-Team3-Puhaha pull request #27
Opened 2022-07-26 01:24 UTC by teethemoji

## ✅ 관련 이슈

Fork Tool 제작 뷰 구현 (#7)

 ## ✅ 구현/변경 사항 및 이유
- SceneKit을 사용해 포크, 스푼, 거품기, 뒤집개를 3D 오브젝트로 제작하고 화면 상단의 Scene 안에 불러옵니다.
- 탭한 종류 버튼에 따라서 화면에 보여지는 오브젝트를 교체합니다.
- 탭한 색상 버튼에 따라서 화면에 보여지는 오브젝트의 색상을 교체합니다.
- 탭한 버튼에는 까만 테두리를 둘러줍니다.

 ## ✅ PR Point

러프하게 작업하느라 코드가 많이 지저분합니다.. 300줄이 넘어가버려서 코드를 좀 분리하고 싶은데 어떤 방법이 좋을까요?

 ## ✅ 참고 사항

![포크제작뷰구현](https://user-images.githubusercontent.com/60784937/180901610-f6a6e8f7-9984-4ec6-8766-10f3a0ce4dcb.gif)

2022-07-26 01:53 UTC, lenamin requested changes
SceneView를 활용한 3D 구현 진짜 너무나 멋집니다 티모~!!!!!!! 존경스러워요!!!!!! 
불필요한 주석이나 개행만 조금 수정해주시면 가독성이 정말 좋아질 것 같습니다. 
남긴 코드리뷰 참고 부탁드립니다!

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +        buttonsStackView.spacing = 16
이 부분들은 밖에서 따로 선언해주고, arrangedSubView에서 불러오면 가독성이 더 좋아질 것 같습니다

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +
화면 비율에 따라 설정해주는게 좋지 않을까요?

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +            buttonsStackView.widthAnchor.constraint(equalTo: stackView.widthAnchor)
이 부분은 개행만으로도 어떤 부분에 대한 constraint인지 확인할 수 있으므로 주석은 없어도 될 것 같습니당

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +    // MARK: viewDidLoad()
함수명 자체를 굳이 마크주석으로 달아줄 필요는 없어보입니다!

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +    }
배열에 넣어놓고 한번에 activate 하는 방법도 있네요. 새로 하나 알아갑니다!

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +    // MARK: Style Button Pressed Function
이 부분도 코드만으로 의미 파악이 가능하므로 주석은 없어도 될 듯 합니다

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +        case UIImage(systemName: "cloud") :
콜론의 왼쪽 space는 지워주세용..!

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +
개행을 하신 이유가 있을까요? 👀

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +
해당 개행은 불필요해 보입니다!

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +        sceneInsideSceneView?.rootNode.addChildNode(ambientLightNode)
낯선 코드라 해당 내용의 주석을 달아주셔서 의미 파악이 수월했습니다. 

필요한 `SCNNode()` 들을 외부에서 선언한 다음에 해당 UIView로 가져와 사용한다면 가독성이 더 좋아질 것 같습니다 :) 
(외부에서 선언해준 다음 `///` 주석을 통해 해당 UIView 에서 어떤 의미인지 파악할 수 있도록 해주면 어떨까요?)

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +
constraint 부분은 코드만으로 의미파악을 하는 것이 어렵지는 않아서, 주석은 불필요해보이는데 어떻게 생각하시나요?

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +    // MARK: Color Button Pressed Function
이 부분 주석 또한 없더라도 의미파악에는 문제가 없어보입니다!

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +    }
해당 변수 위에 `///`로 색상을 적어준다면 색상을 사용할 때 옵션키를 활용해 확인할 수 있어 편리할 것 같아요.

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +    }
또한 import 부분에서 `UIKit.UIColor` 만 import 해줘도 되지 않을까 합니다.

2022-07-26 01:53 UTC, lenamin commented on Puhaha/Puhaha/Models/PokingTool.swift
> +import Foundation
UIKit이 이미 있으므로 Foundation은 불필요해보입니다. 
UIColor가 필요해 UIKit을 import 하신거라면 여기도 마찬가지로 `UIKit.UIColor`만 import 해주는 건 어떨까요?

2022-07-26 10:37 UTC, SohyeonKim-dev approved these changes
🍴🥄🍚  티모.. 대박 ... . . 👏👏

2022-07-26 10:37 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
> +let toolColors = [UIColor.customLightGray, UIColor.customBlue, UIColor.customYellow, UIColor.customBlack, UIColor.customPurple]
오오옹 다른 색깔로 변했네요?! 😍

2022-07-27 01:47 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +        for i in 0..<toolImages.count {
```swift
for toolImage in toolImages {
```
제안 합니다.

2022-07-27 01:47 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +        let buttonsStackView = UIStackView(arrangedSubviews: [])
```swift
let ... = UIStackView()
```
제안 합니다

2022-07-27 01:47 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +        forkCustomView.addSubview(colorButtonsStackView)
```swift
[sceneView, styleButtonsStackView, colorButtonsStackView].forEach {
    forkCustomView.addSubview($0)
}
```
제안 합니다.

2022-07-27 01:47 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +    private func addConstraints() {
configureConstraints로 이름 수정해주세요

2022-07-27 01:47 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +        constraints.append(forkCustomView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor))
```swift
NSLayoutConstraint.activate([
  forkCustomView.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor),
  ...
])
```
제한합니다.

2022-07-27 01:48 UTC, JIW00NG requested changes
제안한 부분 수정부탁드려요

2022-07-27 02:50 UTC, lenamin requested changes

2022-07-27 02:50 UTC, lenamin commented on Puhaha/Puhaha/Global/Extensioon/UIColor+Extension.swift
티모 초록색 추가해주세요~!

2022-07-27 07:02 UTC, JIW00NG approved these changes
전면 수정이 있었네요.
고생하셨어요!

2022-07-27 07:57 UTC, lenamin approved these changes
고생많으셨습니다!

2022-07-27 08:08 UTC, merged