[FEAT] filter meal card and transition from MealCardViewController to MealDetailViewController
DeveloperAcademy-POSTECH/MC3-Team3-Puhaha pull request #32
Opened 2022-07-27 06:49 UTC by JIW00NG

## ✅ 관련 이슈

 
#31 

 ## ✅ 구현/변경 사항 및 이유

 
* 식구 이름 선택 시, 해당 식구가 올린 사진으로 음식 사진 필터링
* 하단 탭바 색상 변경(피그마 변경사항 적용)
* 음식 사진 선택 시, 해당 음식 사진 디테일 뷰 전환
* 뷰 전환을 위한 navigationController 추가

2022-07-27 06:56 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainViewController.swift
> +        tabBarController?.navigationController?.isNavigationBarHidden = true
여기 개행은 왜 2개인 걸까요? 👀

2022-07-27 07:08 UTC, lenamin requested changes
기존에 수정되지 않은 tagStack 수정 부탁드립니다. 
코멘트 확인 부탁드리고, 의견은 언제든 이야기해주세요!

2022-07-27 07:08 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainViewController.swift
> +    }
이 부분은 mealCardCollectionView가 아닐때가 어떤 경우인지 한번에 파악하기가 힘든데, switch 구문을 활용하면 어떨까요?

2022-07-27 07:08 UTC, lenamin commented on Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
> +        dateFormatter.dateFormat = "h시 m분"
반영 감사합니다

2022-07-27 07:08 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MealDetailViewController.swift
> +        view.layer.masksToBounds = true
해당 코드는 어떤 동작을 위해 viewDidLoad()에 구현된걸까요?

2022-07-27 07:08 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MealDetailViewController.swift
>          uploadedTimeLabel.text = "\(uploadedTime.ampm)\n\(uploadedTime.timeText)"
hoxy...... 오전오후 글자크기를 좀 더 줄여주실 수 있나요.....,,,,, 
개인적인 제안이었습니다....

2022-07-29 02:38 UTC, lenamin approved these changes

2022-07-29 02:38 UTC, lenamin commented
컨플릭 해결만 부탁드립니다 ~!

2022-07-29 04:50 UTC, SohyeonKim-dev approved these changes
열일하시는 cccccccccccto님,, 🥹🥹 감사합니다 . 👏👏

2022-07-29 08:38 UTC, teethemoji approved these changes

2022-07-30 05:21 UTC, merged