[FEAT] 확정된 Hi-Fi를 기반으로 UI 구현 (#36)
DeveloperAcademy-POSTECH/MC3-Team3-Puhaha pull request #44
Opened 2022-07-30 07:49 UTC by teethemoji

## ✅ 관련 이슈

[FEAT] 확정된 Hi-Fi를 기반으로 UI 구현 (#36)

 ## ✅ 구현/변경 사항 및 이유

불확실했던 PokingTool과 enum Tool을 갈고 닦고 광을 냈으며 이전에 작업해둔 프로토타입을 Hi-Fi 디자인을 토대로 수정 및 구현했습니다.
thanks to @skycat0212 

 ## ✅ 참고 사항

![하이파이구현한것촬영](https://user-images.githubusercontent.com/60784937/181880680-f1728e1f-8815-47e1-b7e6-f0e24b03f862.gif)

2022-07-30 07:59 UTC, SohyeonKim-dev approved these changes
🥄👏👏

2022-07-30 07:59 UTC, JIW00NG approved these changes
고생했어요

2022-07-30 07:59 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +    private func willRenderSelectedToolOnly(selectedToolIndex: Int) {
오 했네요

2022-07-30 08:25 UTC, lenamin requested changes
고생하셨습니다. 광나는 Tool 들이 아름답네요.

2022-07-30 08:25 UTC, lenamin commented on Puhaha/Puhaha.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = WhatDidYouEat;
프로비저닝 다시 원래대로 변경해야할 듯 합니다.

2022-07-30 08:25 UTC, lenamin commented on Puhaha/Puhaha/Controllers/PokeToolViewController.swift
> +            print()
빈 프린트는 왜 있는걸까요? 👀

2022-07-30 08:25 UTC, lenamin commented on Puhaha/Puhaha/Models/PokingTool.swift
UIKit.Color 만 import 하는 건 어떨까요?

2022-07-30 12:02 UTC, teethemoji reviewed
프로비져닝 관련 코드 삭제!

2022-07-30 12:02 UTC, teethemoji commented on Puhaha/Puhaha.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = "WhatDidYouEat-adHoc";
```suggestion
```

2022-07-30 12:29 UTC, lenamin approved these changes

2022-07-30 14:19 UTC, teethemoji commented on Puhaha/Puhaha.xcodeproj/project.pbxproj
> +				PROVISIONING_PROFILE_SPECIFIER = WhatDidYouEat;
반영 완료했습니다!

2022-07-30 14:19 UTC, teethemoji commented on Puhaha/Puhaha/Models/PokingTool.swift
반영 완료했습니다👍

2022-07-30 14:20 UTC, merged

2022-07-31 07:37 UTC, skycat0212 commented on Puhaha/Puhaha/Models/PokingTool.swift
> +    }
의견 반영해주셔서 감사합니다!

2022-07-31 07:40 UTC, skycat0212 commented on Puhaha/Puhaha/Models/PokingTool.swift
>      }
`PokeTool`이라는 명명을 하신 이유가 궁금하네용🤓🤓🤓

2022-07-31 08:13 UTC, teethemoji commented on Puhaha/Puhaha/Models/PokingTool.swift
>      }
_콕 찌르기_ 라는 기능에 사용되는 도구이기 때문에 _PokeTool 찌르기도구_ 가 되었습니다🙃