Feature/colli/name setting view
DeveloperAcademy-POSTECH/MC3-Team3-Puhaha pull request #55
Opened 2022-08-06 07:44 UTC by SohyeonKim-dev

## ✅ 관련 이슈

 ## ✅ 구현/변경 사항 및 이유

- NameSettingViewController
- Firestore db 연결
- UserDefaults 설정
- familyViewController 연결

 ## ✅ PR Point

- 유저의 상태를 판별하는 과정이 
1) 어플을 처음 실행하는 sceneDelegate 파일에서 한 번, (UserDefaults에 저장된 가족 코드로 판별)
2) SingInViewControllerASDelegate 에서 로그인 직후 한 번 ,
총 2번 이루어집니다. 
해당 과정의 로직이 올바른지 체크해주세요! (저도 정말 정답이 뭔지 모르겠습니다.. )
- Firestore db 연결이 제대로 되는지 확인 부탁드립니다. (hoxy 모르니깐,,) 
- UserDefaults를 제대로 확인한 것이 맞는지, 또 옵셔널 언래핑이 적절하게 이루어졌는지
- CreateFamily -> (Join/Invite) Family 로 이름을 지정해두었는데, 서버에 연결하는 과정이나 코드 내부에서 헷갈리는 부분이 많을 것 같습니다. 더 좋은 네이밍이 있다고 생각하시면, 수정사항 팍팍 보내주십쇼! (저도 많이 헷갈리더라고요 😇)

- 요구사항이 너무 많..네요 🥲 Sorry.. . 
- 브랜치 따온 지 너무 오래 지나서, 코드가 썩기 전에 PR 올립니다.. ㅋ.ㅋ 🙇‍♀️🙇‍♀️ 어플 출시까지 다들 화이팅팅!! 

 ## ✅ 참고 사항

2022-08-06 10:43 UTC, JIW00NG requested changes
1. 유저 상태 판별과정은 해당 코드 부분에 리뷰 남겼습니다.
2. Firebase 연결은 잘 된 것 같습니다. 다만 연결하는 코드는 재사용을 위해 FirestoreManager, StorageManager에서 함수를 만들어서 호출하는 방식으로 수정해주세요.
3. UserDefaults도 제대로 사용했으나 리뷰에 남겨 놓은 것 처럼 없는 경우는 "" 로 받아왔으면 좋겠습니다.
4. CreateFamily 네이밍은 Join/Invite 좋다고 생각합니다 ㅎㅎ

코드 구현하느라 고생하셨어요👍👍👍
제가 작성해 놓은 부분만 조금 수정 부탁드릴게요.

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Info.plist
> -	<key>NSCameraUsageDescription</key>
해당 부분은 현재 메인에 있는 부분으로 삭제하면 안되는 코드입니다.

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
>          case "이름 변경":
이런 변하지 않는 문자값의 경우 enum 사용을 권장합니다.
예를 들어 다음과 같습니다.

```swift
enum UserSettingLabel: String {
    case changeName = "이름 변경"
    case logout = "로그아웃"
}

let label = UserSettingLabel.changeName

switch label {
case UserSettingLabel.changeName :
    // 이름 변경 뷰 이동
    print("이름 변경")
default:
    print("etc")
}
```

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
> +            UserDefaults.standard.set("", forKey: "loginedUserEmail")
👍

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/CreateFamilyViewController.swift
> +    lazy var inviteNewFamilyRoomButton: UIButton = {
버튼이 lazy 인 이유는 무엇인가요?

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/InviteFamilyViewController.swift
> +        db.collection("Users").document(userEmail).setData(["familyCode": createdRoomCode])
이런 Firestore, storage 관련 코드는 FirestoreManager, StorageManager에서 함수로 지정한 후 호출해 주세요

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/JoinFamilyViewController.swift
> +        db.collection("Users").document(userEmail).setData(["familyCode": joinedRoomCode])
InviteFamilyViewController.swift 와 마찬가지로 FirestoreManager에 함수로 빼주세요

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/JoinFamilyViewController.swift
> +        familyCodeTextField.setUnderLine()
이 함수를 viewDidLayoutSubviews에서 호출하는 이유는 무엇인가요?

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/NameSettingViewController.swift
> +        let signinUserName = nameTextField.text as String? ?? "defaultName"
값이 있고 없고의 차이가 명확하지 않아보이는데
값이 없으면
"defaultName"
이라는 값으로 가져오는데
"" 로 가져오는건 어떨까요?

그럴 일은 거의 없겠지만 정말 사용자가 이름을 "defaultName"으로 설정할 경우도 고려해야 합니다.

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/SignInViewController.swift
> +    lazy var appleLoginButton: ASAuthorizationAppleIDButton = {
1. 버튼 사이즈 조절을 이때 하기 때문에 lazy를 사용하는 것인가요?
2. widthAnchor.constraint()... 부분은 configureConstraints() 안으로 뺄 수 있을 것이라 생각합니다. -> 또한 그런 이유에서 lazy를 사용한 것이 맞다면 private을 그대로 사용하는게 가능할 거라 생각합니다.

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/SingInViewControllerASDelegate.swift
> +            let name = UserDefaults.standard.string(forKey: "name") as String? ?? ""
UserDefaults에서 값을 가져오는 부분이 해당 코드는 없을 경우 "" 인데 다른 부분은 default..."로 들어가고 있어요. 특별한 이유가 없다면 다른 부분도 "" 로 처리해주는게 좋습니다.

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Models/SigninManager.swift
> +    private let userDefaultsEmail = UserDefaults.standard.string(forKey: "loginedUserEmail") as String? ?? "defaultsEmail"
위 내용과 동일합니다. 값이 없을 경우 ""로 받아와주세요

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Models/SigninManager.swift
> +    func getSignInUser(userEmail: String, completion: @escaping () -> Void) {
위 내용과 동일하게 FirestoreManager에 함수를 생성해서 사용해주세요

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/SceneDelegate.swift
> +        if userDefaultsRoomCode == "" {
room code가 아닌 유저가 있는지 없는지로 판단해주세요. 가족에 들어 있지 않은 경우를 고려한 것이라면 userName이 들어있는지도 함께 조건문에 추가해야할 것으로 보입니다.

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/SingInViewControllerASDelegate.swift
> +                destinationViewController = MainTabViewController()
어차피 로그인된 경우는 sceneDelegate에서 바로 확인해서 메인으로 넘어가기 때문에 SignInViewControllerASDelegate에서 처리할 필요가 없어보입니다.

* sceneDelegate에서는 가족코드가 있다면 바로 MainTabView로 넘어가고 SignInViewController에서는 이름이 없고 룸코드가 없을 때 MainTabView로 넘어가는데 그렇다면 이미 앞에서 MainTabView로 넘어가면 넘어 갔지 해당 화면에서 넘어가지는 않을 듯 합니다. UserDefaults의 값만을 비교하는 경우 해당 부분에서 처리는 적절하지 않습니다.
* UserDefaults에서는 로그인이 되지 않은 상태로 값들이 "" 이며, 서버에서 유저의 가족 코드를 가져와해당 상태를 비교해야 하는 경우는 지금처럼 하는 것이 맞다고 생각합니다.

2022-08-06 10:43 UTC, JIW00NG commented on Puhaha/Puhaha/SceneDelegate.swift
> +    private let userDefaultsRoomCode = UserDefaults.standard.string(forKey: "roomCode") as String? ?? ""
제가 지금까지 봐왔던 코드들은 대부분 as String? 이 아닌 as? String 형태를 사용했습니다.
두가지 형태의 타입을 확인해 본 결과 모두 String으로 가져오고 있기 때문에 편하신대로 사용해도 될 것 같아요.

2022-08-06 12:12 UTC, lenamin requested changes
콜리 드디어 로그인을 정복해주셨군요 
너무나 고생하셨습니다. 
함께 저녁도 거르며 코딩한 보람이 있습니다!!!!

2022-08-06 12:12 UTC, lenamin commented on Puhaha/Puhaha/Controllers/InviteFamilyViewController.swift
> +    public var db = Firestore.firestore()
public으로 접근지정을 하신 이유가 궁금합니다! 
다른 ViewController에서도 동일하게 지정해서 사용하고 계셔서 어떤 의도이신지 궁금합니다.

2022-08-06 12:12 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainViewController.swift
> +import FirebaseFirestore
third party의 경우 알파벳 순서로 임포트한다고 합니다. 
+ firstparty와는 한 칸 띄워야한다고 가이드 문서에 나와있더라구요

2022-08-06 12:12 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MainViewController.swift
> +    var loginedUserEmail: String = UserDefaults.standard.string(forKey: "userEmail") ?? "ipkjw2@gmail.com"
옵셔널 바인딩 시 특정 이메일을 하드코딩해주는 것보다는 String()으로 주면 어떨까요?

2022-08-06 12:12 UTC, lenamin commented on Puhaha/Puhaha/Controllers/MealDetailViewController.swift
> +            print("add reaction")
이 Todo 에선 무엇을 추가로 해야하나요?

2022-08-06 12:12 UTC, lenamin commented on Puhaha/Puhaha/Controllers/NameSettingViewController.swift
> +        let signinUserName = nameTextField.text as String? ?? "defaultName"
저는 String()을 한 번 제안해봅니다.

2022-08-06 12:12 UTC, lenamin commented on Puhaha/Puhaha/Controllers/SignInViewController.swift
> +    lazy var appleLoginButton: ASAuthorizationAppleIDButton = {
아마 addTarget 액션 때문일거에요.

2022-08-06 12:15 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/NameSettingViewController.swift
> +        let signinUserName = nameTextField.text as String? ?? "defaultName"
@lenamin String()을 제안하는 이유는 무엇인가요?

2022-08-06 12:16 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/MealDetailViewController.swift
> +            print("add reaction")
@lenamin 이 부분은 제가 한건데 리엑션 추가 버튼을 누르면 일단 저렇게 출력하는 상태로만 구현된 상태입니다. 키 디자인 나오면 그 부분 구현해야해요

2022-08-06 12:40 UTC, lenamin commented on Puhaha/Puhaha/Controllers/NameSettingViewController.swift
> +        let signinUserName = nameTextField.text as String? ?? "defaultName"
하드코딩을 최대한 지양하는것이 좋다고 생각해서 제안해보았습니다.

2022-08-08 00:22 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/CreateFamilyViewController.swift
> +    lazy var inviteNewFamilyRoomButton: UIButton = {
버튼을 Lazy var로 선언하면, ButtonTapped 내부에 동작을 넣을 때, self 관련 warning이 사라지더라고요!
구체적인 원리는... 모르겠습니다. 🙃

2022-08-08 00:23 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/JoinFamilyViewController.swift
> +        db.collection("Users").document(userEmail).setData(["familyCode": joinedRoomCode])
db.collection("Users").document(userEmail).setData(["familyCode": joinedRoomCode])
: db에 접근하는 항목은 모두 manager로 빼면 되는군요! :)

2022-08-08 00:24 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/JoinFamilyViewController.swift
> +        familyCodeTextField.setUnderLine()
viewDidLoad() 내부에서 오류가 나는 부분을 (화면에 그려지지 않는)
viewDidLayoutSubviews 에서 호출하면 그려지는 경우가 종종 있었습니다.! 
마찬가지로 왜인지는.. 모르겠어요 🥲

2022-08-08 00:26 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/MainViewController.swift
> +import FirebaseFirestore
..! 처음 알게 되었어요!! 
수정해두겠습니다! :)

2022-08-08 05:36 UTC, lenamin approved these changes

2022-08-08 05:36 UTC, lenamin commented
conflict 해결 부탁드립니다

2022-08-08 05:38 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Info.plist
> -	<key>NSCameraUsageDescription</key>
✅

2022-08-08 05:38 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Info.plist
> -	<key>NSCameraUsageDescription</key>
✅

2022-08-08 05:49 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/AccountSettingViewController.swift
>          case "이름 변경":
✅ 변경했습니다!
+ delete 기능도 추가로 구현해두겠습니다.

2022-08-08 05:53 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/InviteFamilyViewController.swift
> +    public var db = Firestore.firestore()
저도 저렇게 쓰고 싶지 않았는데,, 
Delegate file로 분리하고, 뷰컨트롤러에서 선언해둔 변수들을 
delegate 파일에서 활용하게 하려다 보니 db를 죄다 public 으로 선언하고 사용했어요
hoxy 더 나은 방법이 있을까요,,? 🥲

2022-08-08 05:56 UTC, teethemoji approved these changes

2022-08-08 06:00 UTC, lenamin commented on Puhaha/Puhaha/Controllers/CreateFamilyViewController.swift
> +    lazy var inviteNewFamilyRoomButton: UIButton = {
https://stackoverflow.com/questions/71682061/why-am-i-getting-this-warning-when-i-add-the-target-to-my-uibutton-in-my-control
이렇다고 합니다

2022-08-08 06:05 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/CreateFamilyViewController.swift
> +    lazy var inviteNewFamilyRoomButton: UIButton = {
오홍

2022-08-08 07:01 UTC, JIW00NG approved these changes
리펙토링은 나중에 하는걸로!

2022-08-08 07:01 UTC, JIW00NG commented on Puhaha/Puhaha/AppDelegate.swift
> +import  FirebaseCore
무슨일이죠

2022-08-08 07:01 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/InviteFamilyViewController.swift
> +    public var db = Firestore.firestore()
delegate를 다른 파일로 따로 뺄 경우 default(internal)로 해도 접근이 가능합니다. public일 필요는 없어요

2022-08-08 08:21 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/NameSettingViewController.swift
> +        let signinUserName = nameTextField.text as String? ?? "defaultName"
엇 다른 부분들에서 ""로 사용한 곳이 많아서, 일단은 ""로 고쳐두었습니다!

2022-08-08 08:23 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/SignInViewController.swift
> +    lazy var appleLoginButton: ASAuthorizationAppleIDButton = {
아아 lazy 버튼은 action 경고때문에 사용한 게 맞습니다! 
그리고 높이 너비 조절은 configureConstraints로 빼는게 맞는 것 같아서
아래부분으로 코드 옮겨서 수정했습니다! :)

2022-08-08 08:26 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Models/SigninManager.swift
> +    private let userDefaultsEmail = UserDefaults.standard.string(forKey: "loginedUserEmail") as String? ?? "defaultsEmail"
default 키워드로 찾아서 다 없앴는데, hozy나 아직 남아 발견된다면,, "" 로 바꿔주십쇼 🙇‍♀️

2022-08-08 08:29 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/AppDelegate.swift
> +import  FirebaseCore
.... Aㅏ.. 착오가 .. 있었습니다. 정상화시켜둘게요... ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2022-08-08 08:29 UTC, teethemoji commented on Puhaha/Puhaha/AppDelegate.swift
> +import  FirebaseCore
저만 궁금한줄

2022-08-09 13:32 UTC, merged