업로드뷰 firebase 데이터 연결
DeveloperAcademy-POSTECH/MC3-Team3-Puhaha pull request #59
Opened 2022-08-11 12:24 UTC by lenamin

## ✅ 관련 이슈

 

 ## ✅ 구현/변경 사항 및 이유
- 이미지 업로드 기능 구현 
- 입력한 태그 정보 firebase로 연결
 

 ## ✅ PR Point
- firestoreManager 에서 set 함수를 만들어쓰고 있는데, 이 함수들이 모두 하나의 유저의 정보에 저장되는 것이 아닌, 따로따로 저장이 되고 있습니다. 이게 로그인을 현재 하지 못해서 생기는 문제인지 확인하기가 어려운 상태인데, 혹시나 코드에 문제가 있다면 언제든지 알려주세요. 
 

 ## ✅ 참고 사항

2022-08-12 01:51 UTC, SohyeonKim-dev approved these changes
👏👏👏👏👏 
업로드 뷰를 뿌시다니,,, 😘
역시 레나는 능히 해냈다!!! 🍄
수고하셨습니다! :)

2022-08-12 01:51 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Models/SigninManager.swift
> +//
,,,! 이 파일이 제가 지웠던 파일 같은데,
특별한 이유가 없다면, 삭제해주세요 :) 

(signinmanager로 혼자서 해보다가,
 우기 pr 받은 뒤에, getSignInUser 함수를
 firestore manager에 합쳤던 걸로 기억합니다!)

2022-08-12 01:51 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +        firestoreManager.setUserName(userEmail: loginedUserEmail, userName: meal.uploadUser)
이 과정은 nameSettingViewController 에서 하는 걸로 알고있는데,
혹시 이 코드가 왜 들어갔는지 알 수 있을까요? 

+ family code 설정도 Invite/join FamilyViewController 에서 합니다!

2022-08-12 08:33 UTC, teethemoji commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +import FirebaseStorage
FirebaseFirestore과 FirebaseStorage를 가진 firestoreManager과 storageManager를 가져오기 때문에 UploadViewController에도 가져올 필요가 있는지 잘 모르겠는데 혹시 가져오는 이유가 있을까요?

2022-08-12 10:14 UTC, lenamin commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +        firestoreManager.setUserName(userEmail: loginedUserEmail, userName: meal.uploadUser)
이미지와 태그만 넣으니까 해당되는 항목만 생성이 되어서 한꺼번에 생성하려고 쓴 코드인데, 
다른 곳에서 해주고 있으면 오히려 이부분 빼고, 이미지랑 태그만 남겨두면 되겠네요!

2022-08-12 10:15 UTC, lenamin commented on Puhaha/Puhaha/Models/SigninManager.swift
> +//
지금은 없어진 상태랍니다. 아마 메인 머지 받아오면서 같이 들어와있는 것 같아요.

2022-08-12 10:15 UTC, lenamin commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +import FirebaseStorage
초반에 데이터를 업로드뷰에서 넣어줄 때 들어간 부분인 것 같아요. 삭제해서 반영해뒀습니다.

2022-08-12 13:53 UTC, JIW00NG requested changes
FirestoreManager.swift의 set함수만 고쳐서 올려주시면 될 것 같습니다.

2022-08-12 13:53 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    var filter: String = "모두"
main.view에서 그대로 가져온거 같은데 안쓰는거 지워주세요

2022-08-12 13:53 UTC, JIW00NG commented on Puhaha/Puhaha.xcodeproj/project.pbxproj
> +		BF42685628A35674003DB735 /* FirebaseFirestoreSwift in Frameworks */ = {isa = PBXBuildFile; productRef = CE33B7902895755E0054F9CD /* FirebaseFirestoreSwift */; };
다음 PR부터는 Firebase관련 부분은 그냥 올리지 말아주세요 매번 추가하고있어서 불필요해보여요

2022-08-12 13:53 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    var meal = Meal.init(mealImage: UIImage(),
meals는 언제쓰고 meal은 언제 사용하는건가요? 사진을 받고 단순히 meal 하나를 firebase firestore에 저장만 하면 될텐데 굳이 meals가 필요할까요?

2022-08-12 13:53 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    override func viewDidDisappear(_ animated: Bool) {
이 부분은 업로드 버튼을 눌렀을 때가 아닌 뷰가 사라질때 실행되야되는 것이 맞나요?

2022-08-12 13:53 UTC, JIW00NG commented on Puhaha/Puhaha/Models/Tag.swift
> +    var content: String
중간에 바뀔 이유가 있을까요?

2022-08-12 13:53 UTC, JIW00NG commented on Puhaha/Puhaha/Manager/FirestoreManager.swift
> +    func setUploadImageIndex(userEmail: String, mealImageName: String, familyCode: String) {
업로드 버튼을 눌렀을 경우 image index, upload user, upload date, upload time을 올리는 것 처럼 보이는데요. 함수 하나로 합쳐서 하는 것이 바람직해 보입니다 예를들어 다음과같이 할 수 있을 것 같아요.

```swift
func setUploadMeal(userEmail: String, familyCode: String, mealImageName: String) {
     db.collection("Families").document(familyCode).collection("Meals").document(mealImageName).setData([
          "mealImageIndex": String(meals.count),
          "uploadUser": userEmail,
          "uploadDate": Date().dateText,
          "uploadTime": Date().timeText
     ])
}
```

2022-08-12 13:53 UTC, JIW00NG commented on Puhaha/Puhaha/Manager/FirestoreManager.swift
> +    func setUploadImageIndex(userEmail: String, mealImageName: String, familyCode: String) {
다른 Meals에 따로따로 저장되는 이유도 이게 한번에 동작하지 않기 때문이라고 생각해요

2022-08-12 13:53 UTC, JIW00NG commented on Puhaha/Puhaha/Manager/StorageManager.swift
> +        metaData.contentType = "image/jpeg"
이렇게 저장하면 jpeg 형식으로 저장되는건가요!?
👍👍👍

2022-08-12 13:53 UTC, JIW00NG commented on Puhaha/Puhaha/Manager/StorageManager.swift
> +        storageRef.child(filePathUser).child(filePathDate).child("\(fileMealImageIndex).jpeg").putData(data, metadata: metaData) { _, error in
크으

2022-08-12 13:53 UTC, JIW00NG commented on Puhaha/Puhaha/Models/Tag.swift
> +    var content: String
내가 넣었나?..

2022-08-12 14:16 UTC, teethemoji approved these changes
수고하셨습니다!

2022-08-12 16:36 UTC, lenamin commented on Puhaha/Puhaha.xcodeproj/project.pbxproj
> +		BF42685628A35674003DB735 /* FirebaseFirestoreSwift in Frameworks */ = {isa = PBXBuildFile; productRef = CE33B7902895755E0054F9CD /* FirebaseFirestoreSwift */; };
넵

2022-08-12 16:36 UTC, lenamin commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    var meal = Meal.init(mealImage: UIImage(),
meal image index를 [Meal] 개수로 하기 때문에 count를 위해 필요합니다. 
혹시 더 좋은 아이디어가 있다면 환영입니다

2022-08-12 16:36 UTC, lenamin commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    override func viewDidDisappear(_ animated: Bool) {
안그래도 이 부분이 찜찜했었는데 수정해볼게요

2022-08-12 16:36 UTC, lenamin commented on Puhaha/Puhaha/Manager/FirestoreManager.swift
> +    func setUploadImageIndex(userEmail: String, mealImageName: String, familyCode: String) {
이렇게 했을 때 에러가 발생했어서 안되는 줄 알았는데, 되는거였군요...!!!!!!! 수정해보겠습니다

2022-08-12 16:36 UTC, lenamin commented on Puhaha/Puhaha/Manager/StorageManager.swift
> +        metaData.contentType = "image/jpeg"
그렇습니다 !

2022-08-12 16:36 UTC, lenamin commented on Puhaha/Puhaha/Models/Tag.swift
> +    var content: String
태그를 입력하는 과정에서 수정이 필요했는데, 굳이 거치지 않아도 될 것 같습니다.

2022-08-12 16:41 UTC, JIW00NG commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    var meal = Meal.init(mealImage: UIImage(),
documents.count는 어떨까요

2022-08-12 17:54 UTC, JIW00NG commented on Puhaha/Puhaha/Manager/FirestoreManager.swift
> +    func setUploadImageIndex(userEmail: String, mealImageName: String, familyCode: String) {
처음 음식 사진을 올리는 것이라면 addDocuments가 맞겠네요 아래는 예제코드입니다

‘’’

// Add a new document with a generated id.
var ref: DocumentReference? = nil
ref = db.collection("cities").addDocument(data: [
    "name": "Tokyo",
    "country": "Japan"
]) { err in
    if let err = err {
        print("Error adding document: \(err)")
    } else {
        print("Document added with ID: \(ref!.documentID)")
    }
}

‘’’

출처 : https://firebase.google.com/docs/firestore/manage-data/add-data#swift_9

2022-08-13 12:36 UTC, lenamin commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    var meal = Meal.init(mealImage: UIImage(),
meals 자체를 documents 로 하자는 의미인가요?

2022-08-14 08:21 UTC, lenamin commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    var filter: String = "모두"
[c8b41de](https://github.com/DeveloperAcademy-POSTECH/MC3-Team3-Puhaha/pull/59/commits/c8b41de817f9bf2089adba9ef42d0fd0a087cb15) 반영했습니다.

2022-08-14 08:21 UTC, lenamin commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    var meal = Meal.init(mealImage: UIImage(),
덕분에 해결했습니다. 이 부분 Date와 time으로 저장하기로 했습니다!!

2022-08-14 08:22 UTC, lenamin commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    override func viewDidDisappear(_ animated: Bool) {
[8bf8078](https://github.com/DeveloperAcademy-POSTECH/MC3-Team3-Puhaha/pull/59/commits/8bf807804be1eaa516ff67b9b02886fcc1b15902) 수정했습니다

2022-08-14 08:22 UTC, lenamin commented on Puhaha/Puhaha/Manager/FirestoreManager.swift
> +    func setUploadImageIndex(userEmail: String, mealImageName: String, familyCode: String) {
덕분에 해결....!!!!!!!! 감사합니다

2022-08-14 08:31 UTC, JIW00NG approved these changes
귣귣👍👍👍👍

2022-08-14 08:32 UTC, merged