Feature/woogy/achieving
DeveloperAcademy-POSTECH/MC3-Team3-Puhaha pull request #60
Opened 2022-08-12 10:25 UTC by JIW00NG

## ✅ 구현/변경 사항 및 이유

 
* 사진 모아보기 페이지 view 그리기
* 달력에 선택된 날짜에 따라 음식 사진 필터링
* 사진 모아보기 firebase 데이터 가져오기

 ## ✅ 참고 사항

 
현재 Firestore에 이미지의 인덱스로 저장되어 있기 때문에 인덱스로 접근하여 이미지를 가져오고 있습니다. 추후 전체 파일명(파일 형식 포함)으로 저장하게 된다면 파일명으로 가져오도록 수정하겠습니다.

__스크린샷__
![Simulator Screen Shot - iPhone 13 mini - 2022-08-12 at 19 22 58](https://user-images.githubusercontent.com/56468120/184335617-88145716-52b9-4061-abd6-14da8f757415.png)

2022-08-12 16:55 UTC, lenamin approved these changes
아카이빙 뷰까지 완벽구현. 수고하셨습니다 ~!

2022-08-12 16:55 UTC, lenamin commented on Puhaha/Puhaha/Global/Extensioon/Date+Today.swift
> +    }
개인적인 의견인데, 월과 일에서 한 자리수인 경우 앞에 있는 0이 표시되지 않도록 해주는건 어떨까요?

2022-08-12 16:55 UTC, lenamin commented on Puhaha/Puhaha/Global/Extensioon/ShadowUIViewExtension.swift
> +}
shadow 설정을 이렇게 따로 빼주셨군요. 👍

2022-08-12 16:55 UTC, lenamin commented on Puhaha/Puhaha/Manager/FirestoreManager.swift
>                  return
👍

2022-08-12 23:48 UTC, SohyeonKim-dev approved these changes
wow,,,, 빠른 구현 놀랍습니다.. 🙇‍♀️🙇‍♀️
수고하셨어요!! 👏👏👏

2022-08-12 23:48 UTC, SohyeonKim-dev commented on Puhaha/Puhaha/Manager/FirestoreManager.swift
>                  return
👍👍👍

2022-08-15 05:00 UTC, teethemoji requested changes
수고하셨습니다 이름 관련 피드백 확인해주세요!

2022-08-15 05:00 UTC, teethemoji commented on Puhaha/Puhaha.xcodeproj/project.pbxproj
> +		CE445BE728A41ABE0084A93F /* AchieveViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = CE445BE628A41ABE0084A93F /* AchieveViewController.swift */; };
```suggestion
		CE445BE728A41ABE0084A93F /* ArchiveViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = CE445BE628A41ABE0084A93F /* ArchiveViewController.swift */; };
```
Archive(보관하다)를 사용하면 좋을 것 같습니다

2022-08-15 05:00 UTC, teethemoji commented on Puhaha/Puhaha.xcodeproj/project.pbxproj
> +		CE445BE928A426C00084A93F /* AchieveCell.swift in Sources */ = {isa = PBXBuildFile; fileRef = CE445BE828A426C00084A93F /* AchieveCell.swift */; };
```suggestion
		CE445BE928A426C00084A93F /* ArchiveCell.swift in Sources */ = {isa = PBXBuildFile; fileRef = CE445BE828A426C00084A93F /* ArchiveCell.swift */; };
```
뷰컨트롤러 파일 명을 바꾸게 되신다면 셀 명도 같이 바꿔주시면 👍

2022-08-15 05:00 UTC, teethemoji commented on Puhaha/Puhaha.xcodeproj/project.pbxproj
> +		CE45191728A8E0EC00D1FB21 /* String+Extenstion.swift in Sources */ = {isa = PBXBuildFile; fileRef = CE45191628A8E0EC00D1FB21 /* String+Extenstion.swift */; };
```suggestion
		CE45191728A8E0EC00D1FB21 /* String+Extension.swift in Sources */ = {isa = PBXBuildFile; fileRef = CE45191628A8E0EC00D1FB21 /* String+Extension.swift */; };
```
오타 수정합니다

2022-08-15 10:54 UTC, lenamin approved these changes

2022-08-15 12:11 UTC, teethemoji approved these changes
수고하셨습니다👍👏🥳

2022-08-15 12:36 UTC, merged