[FEAT] 업로드뷰 동적 레이아웃 적용
DeveloperAcademy-POSTECH/MC3-Team3-Puhaha pull request #68
Opened 2022-08-18 07:48 UTC by lenamin

## ✅ 관련 이슈
#67 
 

 ## ✅ 구현/변경 사항 및 이유
- iPhone8에서 collectionView 아래부분이 잘리는 문제가 있어, 기기에 따라 동적으로 변하도록 수정하였습니다. 
- 태그를 불러올 때 @JIW00NG 의 함수를 사용할 수 있도록 수정하였습니다. thanks to @JIW00NG

2022-08-18 07:53 UTC, teethemoji commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +    private let systemframe = UIScreen.main.bounds
```suggestion
    private let systemFrame = UIScreen.main.bounds
```
🐫

2022-08-18 07:59 UTC, teethemoji commented on Puhaha/Puhaha/Controllers/UploadViewController.swift
> +        layout.sectionInset = UIEdgeInsets(top: 0, left: UIScreen.main.bounds.width / 17.73, bottom: 0, right: UIScreen.main.bounds.width / 17.73)
```suggestion
        layout.sectionInset = UIEdgeInsets(top: 0, left: systemFrame.width / 17.73, bottom: 0, right: UIScreen.main.bounds.width / 17.73)
```

2022-08-18 08:01 UTC, teethemoji commented on Puhaha/Puhaha/Global/UIViews/TagLabel.swift
> +        tagLabel.frame = CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width / 5.87, height: UIScreen.main.bounds.height / 28.13)
```suggestion
        tagLabel.frame = CGRect(x: 0, y: 0, width: systemFrame.width / 5.87, height: UIScreen.main.bounds.height / 28.13)
```
여기도 사용 가능할듯요

2022-08-18 08:02 UTC, teethemoji commented on Puhaha/Puhaha/Global/UIViews/TagLabel.swift
> +        tagBackground.frame = CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width / 5.87, height: UIScreen.main.bounds.height / 28.13)
```suggestion
        tagBackground.frame = CGRect(x: 0, y: 0, width: systemFrame.width / 5.87, height: systemFrame.height / 28.13)
```

2022-08-18 08:04 UTC, teethemoji requested changes
코멘트 확인해주십쇼🫡

2022-08-18 08:05 UTC, teethemoji approved these changes
👍👍👍

2022-08-19 07:05 UTC, SohyeonKim-dev approved these changes
수고하셨어요!! 👏👏👏

2022-08-19 07:05 UTC, merged